config/routes.rb
Rails.application.routes.draw do
  get 'e_sources/index'

  get 'e_sources/show'

  get 'e_sources/request'

  get 'e_sources/download'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :posts, only: [:index, :show] do
    member do
      get 'like'
    end
  end

  resources :photos, only: [:index, :show] do
    member do
      get 'like'
    end
  end

  root 'home#index'

  devise_for :users

end

app/models/photo.rb
require 'net/http'
require "open-uri"
class Photo
  include Mongoid::Document
  include Mongoid::Timestamps
  include Likeable
  include Countable
  include Tagable
  field :title, type: String
  field :file, type: String
  field :raw_exif, type: Hash
  field :url_name, type: String
  field :content_in_a_list, type: Boolean, default: false
  field :main_color, type: String, default: 'fff'

  index created_at: -1

  mount_uploader :file, PhotoUploader

  after_create do
    #self.get_EXIF
    #self.get_main_color
  end

  def to_param  
    "#{id}#{(url_name)?('-' + url_name.gsub(' ','-')):('')}"  
  end

  def next_post
    @photos = Photo.all.sort_by(&:id).to_a
    if @photos.size > 1
      @photos[(@photos.index(self) + 1) % @photos.size]
    else
      nil
    end
  end

  # 七牛图片处理
  def self.qiniu_methods(*arg)
    arg.each do |m|
      self.class_eval %Q{
        def #{m}
          self.file.url + '-#{m}'
        end
      }
    end
  end

  qiniu_methods :xlarge, :square, :small, :large

  # 从七牛获取 EXIF 和 主要色彩
  def get_EXIF
    data = nil
    open(self.file.url + '?exif') do |http|
      data = http.read
    end
    self.raw_exif = JSON.parse data
    self.save
  end

  def get_main_color
    data = nil
    open(self.file.url + '?imageAve') do |http|
      data = http.read
    end
    self.main_color = JSON.parse(data)["RGB"][2..-1]
    self.save
  end

  # 判断图片明暗
  def light_rage
    r, g, b = self.main_color[0..1], self.main_color[2..3], self.main_color[4..5]
    # 亮度计算公式
    return ((r.to_i(16) * 299 + g.to_i(16) * 587 + b.to_i(16) * 114) / 1000)
  end

  def dark?
    self.light_rage > 500 ? false : true
  end

  # 图片边框颜色，暗色图片黑框(#242424)，亮色用白框(#fff)
  def border_color
    self.dark? ? "#242424" : "#fff"
  end

  # 主要exif信息
  def exif
    data = self.raw_exif
    {
      model: data["Model"]["val"],
      iso: data["ISOSpeedRatings"]["val"],
      shutter: data["ExposureTime"]["val"],
    }
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, except: :index
  def index
    params[:page] ||= 1
    @photos = Photo.all.page params[:page]
  end

  def show
    @liked = liked?
    @photo.visit
    @next_photo = @photo.next_post
  end

  def like
    unless liked?
      @photo.do_like
      session["liked_photo_#{@photo.id}".to_sym] = @photo.id
      puts "liked_#{@photo.id}".to_sym, session["liked_#{@photo.id}".to_sym]
      @flag = :like
    else
      @photo.dislike
      session["liked_photo_#{@photo.id}".to_sym] = nil
      @flag = :dislike
    end
  end

    private
  def set_photo
    @photo = Photo.find /^(\d*)/.match(params[:id]).captures.join('')
    unless @photo.raw_exif
      @photo.get_EXIF
      @photo.get_main_color
    end
  end

  def liked?
    if @photo
      !!(session["liked_photo_#{@photo.id}".to_sym])
    else
      false
    end
  end
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/views/photos/index.html.slim
- content_for :nav_info do
  .title.item
    | Photo
  .input.item.icon
    input.search placeholder="Search..."
    i.fa.fa-search




.container
  .things.transitions-enabled.infinite-scroll.clearfix
    - for photo in @photos
      = link_to photo_path(photo), class: 'thing box'
        /.thumb style="background-image: url(#{photo.small})"
        = image_tag photo.small
        .content
          .preview
            = photo.title
      = paginate @photos, :window => 2, :outer_window => 3

javascript:
  $(function(){
    $('.things').masonry({
        itemSelector: '.thing',
        columnWidth: 8,
        gutterWidth: 0
      });
    console.log('run this')
  })
  
    
 

app/views/photos/like.js.erb
<%- info = "post.#{@flag.to_s}" %>
window.notification.info("<%= t(info) %>");
$('#liked').toggleClass('active');
$('#big_like').toggleClass('active');
$('#liked_people').text("<%= @photo.like %> People Liked.");

app/views/photos/show.html.slim
- content_for :nav_info do
  a.avatar
    = image_tag 'avatar.jpg'

- bg_color = @photo.main_color
- bg_o = 0.2
.linear-header style="#{linear_top_to_bottom('rgba(255,255,255,0)', c_to_a(bg_color, bg_o))}"
.image-display style="background-color:#{c_to_a(bg_color, bg_o)}"
  /.bg style="background-image: url(#{@photo.file.url})"
  .image
    = image_tag @photo.xlarge, class: 'full-width', style: "border-color: #{@photo.border_color}"
  .title
    = @photo.title
  - if @photo.raw_exif
    .exif
      .container
        - for (k,v) in @photo.exif
          .exif_block
            span.title = t("photo.#{k}")
            = v
.after style="#{linear_top_to_bottom(c_to_a(bg_color, bg_o), 'rgba(255,255,255,0)')}"
.container
  .actions.clearfix
    = link_to like_photo_path(@photo), class: "btn blue #{(@liked)?('active'):('')}", id: 'big_like', remote: true
      i.fa.fa-heart-o
      |  Like
    span#liked_people.hide-m
      = @photo.like
      | People Liked.
    a.btn.right
      i.fa.fa-angle-down
    a.btn.right
      i.fa.fa-bookmark-o
    a.btn.right
      i.fa.fa-share-alt
  - if @photo.tags
    .tags
      span.title TAGED IN
      - for tag in @photo.tags_array
        a.tag
          = tag
.info
  .author
    a.avatar
      = image_tag 'avatar.jpg'
    .text
      h3.name
        = Settings.author.name
      p
        = Settings.author.description

  
- content_for :tab do

  .controlTab
    .item.name.hide-xm
      a.avatar.round
        = image_tag 'avatar.jpg'
      a
        = Settings.author.name
      span.timeago.hide-m
        = timeago_tag @photo.created_at, :nojs => true, :limit => 100.days.ago
    .right
      .item.hide-xm
        = @photo.viewer
        |  People read
      = link_to like_photo_path(@photo), class: "item #{(@liked)?('active'):('')} margin-left-xm", id: 'liked', remote: true
        i.fa.fa-heart-o
      a.item
        i.fa.fa-bookmark-o
      a.item
        i.fa.fa-share-alt
      - if @next_photo
        = link_to 'NEXT PHOTO', @next_photo, class: 'item tab'
  style
    | body>main>.info {padding-bottom: 100px;}