config/routes.rb
Rails.application.routes.draw do
  get 'e_sources/index'

  get 'e_sources/show'

  get 'e_sources/request'

  get 'e_sources/download'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :posts, only: [:index, :show] do
    member do
      get 'like'
    end
  end

  resources :photos, only: [:index, :show] do
    member do
      get 'like'
    end
  end

  root 'home#index'

  devise_for :users

end

app/models/post.rb
require "redcarpet"
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include Likeable
  include Countable
  include Tagable
  include ActionView::Helpers
  field :title, type: String
  field :url_name, type: String
  field :subtitle, type: String
  field :content, type: String

  def to_param  
    "#{id}#{(url_name)?('-' + url_name.gsub(' ','-')):('')}"  
  end

  def next_post
    @posts = Post.all.to_a
    if @posts.size > 1
      @posts[(@posts.index(self) + 1) % @posts.size]
    else
      nil
    end
  end

  def render(options = {})
    # XXX: the renderer instance should be a class variable

    options[:hard_wrap] ||= false
    options[:class] ||= ''
    assembler = Redcarpet::Render::HTML.new(:hard_wrap => options[:hard_wrap]) # auto <br> in <p>

    renderer = Redcarpet::Markdown.new(assembler, {
      :autolink => true,
      :fenced_code_blocks => true
    })
    return sanitize(MarkdownConverter.convert(self.content))
  end

  def preview
    text = self.subtitle || self.content
    return truncate(MarkdownConverter.convert(text).remove_html_tag!, length: 100, truncate_string: "...")
  end

  def length
    self.text_content.length
  end

  def text_content
    MarkdownConverter.convert(self.content).remove_html_tag!
  end

  def read_time
    ((self.length / 500.0) * 10).floor / 10.0
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, except: :index
  def index
    params[:page] ||= 1
    @posts = Post.all.page params[:page]
  end

  def show
    @liked = liked?
    @post.visit
    @next_post = @post.next_post
  end

  def like
    unless liked?
      @post.do_like
      session["liked_post_#{@post.id}".to_sym] = @post.id
      puts "liked_#{@post.id}".to_sym, session["liked_#{@post.id}".to_sym]
      @flag = :like
    else
      @post.dislike
      session["liked_post_#{@post.id}".to_sym] = nil
      @flag = :dislike
    end
  end

  private
  def set_post
    @post = Post.find /^(\d*)/.match(params[:id]).captures.join('')
  end

  def liked?
    if @post
      !!(session["liked_post_#{@post.id}".to_sym])
    else
      false
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.slim
- content_for :nav_info do
  .title.item
    | Blog
  .input.item.icon
    input.search placeholder="Search..."
    i.fa.fa-search




.container
  .things.transitions-enabled.infinite-scroll.clearfix
    - for post in @posts
      = link_to post_path(post), class: 'thing box'
        .content
          .title
            = post.title
          .preview
            = post.preview
    = paginate @posts, :window => 2, :outer_window => 3

javascript:
  $(function(){
    $('.things').masonry({
        itemSelector: '.thing',
        columnWidth: 8,
        gutterWidth: 0
      });
    console.log('run this')
  })

app/views/posts/like.js.erb
<%- info = "post.#{@flag.to_s}" %>
window.notification.info("<%= t(info) %>");
$('#liked').toggleClass('active');
$('#big_like').toggleClass('active');
$('#liked_people').text("<%= @post.like %> People Liked.");

app/views/posts/show.html.slim
- content_for :nav_info do
  a.avatar
    = image_tag 'avatar.jpg'

.container
  .header
    h1.title = @post.title
    h5.subtitle = @post.subtitle
  article
    = @post.render
  .actions.clearfix
    = link_to like_post_path(@post), class: "btn blue #{(@liked)?('active'):('')}", id: 'big_like', remote: true
      i.fa.fa-heart-o
      |  Like
    span#liked_people.hide-m
      = @post.like
      | People Liked.
    a.btn.right
      i.fa.fa-angle-down
    a.btn.right
      i.fa.fa-bookmark-o
    a.btn.right
      i.fa.fa-share-alt
  - if @post.tags
    .tags
      span.title TAGED IN
      - for tag in @post.tags_array
        a.tag
          = tag
.info
  .author
    a.avatar
      = image_tag 'avatar.jpg'
    .text
      h3.name
        = Settings.author.name
      p
        = Settings.author.description

- content_for :tab do

  .controlTab
    .item.name.hide-xm
      a.avatar.round
        = image_tag 'avatar.jpg'
      a
        = Settings.author.name
      span.timeago.hide-m
        = timeago_tag @post.created_at, :nojs => true, :limit => 100.days.ago
    .right
      .item.hide-xm
        = @post.viewer
        |  People read
      = link_to like_post_path(@post), class: "item #{(@liked)?('active'):('')} margin-left-xm", id: 'liked', remote: true
        i.fa.fa-heart-o
      a.item
        i.fa.fa-bookmark-o
      a.item
        i.fa.fa-share-alt
      - if @next_post
        = link_to 'NEXT POST', @next_post, class: 'item tab'
  style
    | body>main>.info {padding-bottom: 100px;}